version: '3.5'

services:
  ldi-orchestrator:
    image: ldes/ldi-orchestrator:1.12.0-SNAPSHOT
    container_name: ldi-orchestrator
    ports:
      - "8082:8080"
    volumes:
      - ./ldio.config.yaml:/ldio/application.yaml:ro
    depends_on:
      repository-initializer:
        condition: service_completed_successfully
    networks:
      - subject-pages-network

  graph-db:
    image: eclipse/rdf4j-workbench:latest
    container_name: rdf4j-server
    environment:
      - "JAVA_OPTS=-Xms1g -Xmx4g"
    ports:
      - "8080:8080"
    networks:
      - subject-pages-network

  repository-initializer:
    image: ubuntu
    command: "/bin/sh /initializer/initialize.sh"
    container_name: rdf4j-server-repo-initializer
    volumes:
      - ./repository-initializer:/initializer:ro
    depends_on:
      graph-db:
        condition: service_started
    networks:
      - subject-pages-network

  trifid:
    image: vsds/trifid
    build:
      context: ./trifid
    container_name: trifid
    ports:
      - "8888:8080"
    volumes:
      - ./trifid/config.yaml:/app/config.yaml:ro
      - ./trifid/welcome.hbs:/app/welcome.hbs:ro
    environment:
      - TRIFID_CONFIG=./config.yaml
    networks:
      - subject-pages-network
    depends_on:
      repository-initializer:
        condition: service_completed_successfully

networks:
  subject-pages-network:
    driver: bridge
    name: subject-pages-network

